### ISSUE TITLE
How to use CEMU for difftest?

### ISSUE THREAD

**Issue by Coekjan** [cyyself/cemu#1]
Maybe information about **difftest** is missing from the repo quoted at:

https://github.com/cyyself/cemu/blob/e90f95e2b749c84a75fc3b35262b4346ccc8dc15/README.md?plain=1#L5

Would you please show a demo for "How to use CEMU for difftest"?

**Comment by cyyself** [comment]
Thanks for you attention.

There is a difftest demo for MIPS32 NSCSCC at [https://github.com/cyyself/soc-simulator/blob/master/src/sim_mycpu.cpp](https://github.com/cyyself/soc-simulator/blob/master/src/sim_mycpu.cpp).

**Comment by Coekjan** [comment]
I found the demo in it, thanks a lot.
