### ISSUE TITLE
Solution to extension `zicsr' required error when compiling

### ISSUE THREAD

**Issue by DreamChaser-luzeyu** [cyyself/cemu#7]
The `zicsr` instruction set was made separate as an extension. We have to build opensbi with `PLATFORM_RISCV_ISA=rv64ima_zicsr_zifencei`.

For older linux kernel version, refer to [this solution](https://www.spinics.net/lists/kernel/msg4223898.html).

**Comment by cyyself** [comment]
You are right. This issue was caused by the GCC update, which is in commit [b03be74bad08c382da47e048007a78fa3fb4ef49](https://github.com/riscv-collab/riscv-gcc/commit/b03be74bad08c382da47e048007a78fa3fb4ef49). I fixed the docs to support newer version of GCC. Thanks for reporting.
